### ISSUE TITLE
Planner create first step

### ISSUE THREAD

**Issue by pjiny92** [Travelit-team/travelit#11]
# Description

# To-do
- [ ] HTML : Planner create first step
- [ ] CSS : Planner create first step
- [ ] JS : Planner create first step
- [ ] Back-end : Planner create first step

# ETC
