### ISSUE TITLE
Planner Create Second-step

### ISSUE THREAD

**Issue by pjiny92** [Travelit-team/travelit#14]
# Description

# To-do
- [ ] Front-end : 여행 일차
- [ ] Back-end : 여행 일차
- [ ] Front-end : 찜 장소
- [ ] Back-end :  찜 장소
- [ ] Front-end :  일차  스케줄
- [ ] Back-end :  일차 스케줄

# ETC
