### ISSUE TITLE
지역 정보 리스트 화면 및 기능 구현

### ISSUE THREAD

**Issue by sksrpf1126** [Travelit-team/travelit#7]
# Description

지역 정보 리스트 화면 및 기능 구현

# To-do
- [ ] 지역 정보 리스트 화면 구현  
- [ ] 지역 정보 좋아요 순 TOP5 구현 (임의의 좋아요 데이터로)  
- [ ] 지역 정보 리스트 페이징 처리 구현
- [ ] 지역 카테고리에 따른 화면 및 로직 구현
- [ ] 즐겨찾기 리스트 기능 및 페이징 처리 구현

# ETC
