### ISSUE TITLE
지역 정보 상세 페이지 및 기능 구현

### ISSUE THREAD

**Issue by sksrpf1126** [Travelit-team/travelit#8]
# Description
지역 정보 상세 페이지 및 기능 구현

# To-do
- [ ] 지역 정보 상세 페이지 구현
- [ ] 지역 정보 좋아요 기능 구현
- [ ] 좋아요, 즐겨찾기 수 기능 구현
- [ ] 해당 지역 위치에 대한 지도 API 구현
- [ ] 댓글 기능 구현
- [ ] 최근 본 목록 TOP5 기능 구현

# ETC
