### ISSUE TITLE
Planner Create Frist-step

### ISSUE THREAD

**Issue by pjiny92** [Travelit-team/travelit#9]
# Description

# To-do
- [x] Front-end : 캘린더 
- [x] Back-end : 캘린더
- [x] Front-end : 카드 형식 여행지 다중 선택
- [x] Back-end : 카드 형식 여행지 다중 선택
- [x] Front-end : 여행 제목
- [x] Back-end : 여행 제목
# ETC
